apiVersion: v2
name: node-example
description: Template helm chart for a basic webapp
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: advana-library
    version: 1.0.13
    repository: oci://231388672283.dkr.ecr.us-gov-west-1.amazonaws.com/tenant
    tags:
      - library
  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
  - name: redis
    version: 17.3.8
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - database
