apiVersion: v2
name: advana-marketplace
description: Template helm chart for a basic webapp
type: application
version: 1.0.4
appVersion: 1.0.4

dependencies:
  - name: advana-library
    version: 2.0.3
    repository: oci://231388672283.dkr.ecr.us-gov-west-1.amazonaws.com/tenant
    tags:
      - library

