###############################################################################
## Global Values                                                             ##
###############################################################################

namespace: advana-marketplace
global:
  awsRegion: us-gov-west-1
  appName: advana-marketplace
  baseDomain: app.advana.cdao.us
  registry: 231134345536.dkr.ecr.us-gov-west-1.amazonaws.com
  vaultPrefix: aws/csn/dev/advana-marketplace

###############################################################################
## Default Values                                                            ##
###############################################################################

image:
  repository: tenant/images/advana-marketplace
  pullPolicy: Always

serviceAccount:
  name: "{{ $.Release.Name }}"
  create: true
  annotations:
    eks.amazonaws.com/role-arn: aws-role-arn

ingress:
  enabled: true
  tls: false
  # gateways:  # set to use gateways instead of ingress
  #   - istio-system/public
  # className: nginx  # set if default IngressClass is not configured
  # annotations:
  #   ingress.kubernetes.io/ssl-redirect: 'true'
  #   ingress.kubernetes.io/proxy-body-size: '0'
  #   nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  #   nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
  #   nginx.ingress.kubernetes.io/proxy-body-size: '0'
  domain: "{{ $.Values.global.appName }}.{{ $.Values.global.baseDomain }}"
  hosts:
    "{{ $.Values.ingress.domain }}":
      paths:
        - path: /
          pathType: Prefix
          deploymentName: web
          serviceType: ClusterIP
          serviceName: http

crossplane: 
  postgres:
    enabled: false
    apiVersion: database.advana.cdao.us/v1alpha1
    kind: Postgres
    metadata:
      name: "{{ $.Release.Name }}"
      namespace: "{{ $.Release.Name }}"
    spec:
      region: "{{ $.Values.global.awsRegion }}"
      dbName: "marketplace"
      allocatedStorage: 40  # units: GiB
      # deletionPolicy: Delete
      deletionPolicy: Orphan
      tags:
        application: "{{ $.Release.Name }}"
        description: "RDS Postgres for {{ $.Release.Name }}"
        poc: "yolo@foo.bar"
        pocTeam: "{{ $.Release.Name }} team"
      writeConnectionSecretToRef:
        name: secret-env-crossplane

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

podSecurityContext:
  # the node:node user defined in the chainguard base images is 65532:65532
  # https://edu.chainguard.dev/chainguard/chainguard-images/reference/node-fips/
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532

deployment:
  web:
    replicaCount: 2 # unused if autoscaling is enabled
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80
    podDisruptionBudget:
      minAvailable: 1
      # maxUnavailable: "50%"
    podAnnotations:
      iam.amazonaws.com/role: aws-role-arn
    serviceAccountName: "{{ $.Release.Name }}"
    # initContainer:
    # 01-postgresql-advana-ready:
    #   # postgres-ready script installed by @advana/sequelize module
    #   args:
    #     - node_modules/.bin/postgres-ready
    #     - --host
    #     - $(PG_HOST)
    #     - --port
    #     - $(PG_PORT)
    #     - --database
    #     - $(PG_UM_DB)
    #     - --user
    #     - $(PG_USER)
    #     - --password
    #     - $(PG_PASSWORD)
    #   envFrom:
    #     - secretRef:
    #         name: public-env-db-postgresql
    #     - secretRef:
    #         name: secret-env-db-postgresql
    #     - secretRef:
    #         name: public-env-web

    # 02-postgresql-app-ready: *postgresql-app-ready-init-container

    # 03-postgresql-app-migration-ready:
    #   # migration-ready script installed by @advana/sequelize module
    #   args:
    #     - node_modules/.bin/migration-ready
    #   envFrom:
    #     - secretRef:
    #         name: public-env-db-postgresql
    #     - secretRef:
    #         name: secret-env-db-postgresql
    #     - secretRef:
    #         name: public-env-web

    # 04-redis-ready:
    #   # redis-ready script installed by @advana/redis-client module
    #   args:
    #     - node_modules/.bin/redis-ready
    #   envFrom:
    #     - secretRef:
    #         name: public-env-db-redis
    #     - secretRef:
    #         name: secret-env-db-redis
    #     - secretRef:
    #         name: public-env-web

    container:
      web:
        # args: ["./index.js"] # Removed - nginx doesn't need custom args
        envFrom:
          - secretRef:
              name: public-env-platform-ui
        startupProbe: # checks if container is reachable accounting for startup delays
          httpGet:
            scheme: HTTP
            path: /
            port: http
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe: # checks if container is reachable
          httpGet:
            scheme: HTTP
            path: /
            port: http
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe: # checks if container is ready to receive traffic
          httpGet:
            scheme: HTTP
            path: /
            port: http
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources: # only set values in environment-specific overrides
          limits:
            cpu: 0
            memory: 0Mi
          requests:
            cpu: 0
            memory: 0Mi
        securityContext:
          readOnlyRootFilesystem: false
    nodeSelector: {}
    tolerations: []
    affinity: {}
    service:
      ClusterIP:
        ports:
          http:
            protocol: TCP
            port: 80 # k8s service port
            targetPort: 7500 # internal container port

env:
  secret:
    "public-env-platform-ui":
      secretName: public-env-platform-ui

volume:
  emptyDir:
    "node-logs":
      config:
        sizeLimit: 1Gi
      volumeMount:
        mountPath: "/home/node/.npm/_logs/"
        readOnly: false
  secret:
    "secret-volume-ca-bundle-crt":
      secretName: secret-volume-ca-bundle-crt # reference existing secret if data is not defined
      config:
        defaultMode: 444
        optional: true
      volumeMount:
        mountPath: "/etc/ssl/certs/ca-bundle.crt"
        subPath: "ca-bundle.crt" # only mounts a single file if defined
        readOnly: true

# public values that are stored as a secret object for convenience, remove if using values from vault
secret:
  env:
    secret:
      "public-env-platform-ui":
        data:
          REACT_APP_NODE_ENV: "nipr" # nipr, sipr or jwics
          REACT_APP_ENCLAVE: "advana" # advana or jupiter
          REACT_APP_FAVICON_URL: "favicon.ico"
          REACT_APP_CLASSIFICATION_BANNER: "UNDEFINED CLASSIFICATION"
          REACT_APP_CLASSIFICATION_BANNER_COLOR: "BLACK"
          REACT_APP_CLASSIFICATION_BANNER_TEXT_COLOR: "WHITE"
          REACT_APP_COOKIE_DOMAIN: ".{{ $.Values.global.baseDomain }}"

          REACT_APP_LOGIN_ROUTE: "https://{{ $.Values.ingress.domain }}/login"
          REACT_APP_CMS_ENDPOINT: "https://{{ $.Values.ingress.domain }}/api"
          REACT_APP_USER_TOKEN_ENDPOINT: "https://{{ $.Values.ingress.domain }}/api/auth/token"

          REACT_APP_BANNERS_ENDPOINT: "https://admin.{{ $.Values.global.baseDomain }}/api/banners"
          REACT_APP_MEGA_MENU_ENDPOINT: "https://admin.{{ $.Values.global.baseDomain }}/api/menu/links"
          REACT_APP_MEGA_MENU_BASE_DOMAIN: "https://{{ $.Values.global.baseDomain }}"
          REACT_APP_MEGA_MENU_HEADER_SORT_ORDER: "Domains,Tools,Communities,Help,About"
          REACT_APP_MEGA_MENU_HIGHLIGHT_COLOR: "#56B1AC"
  volume:
    secret:
      "secret-volume-ca-bundle-crt":
        data:
          "ca-bundle.crt": |
            -----BEGIN CERTIFICATE-----
            ca-bundle-pem
            -----END CERTIFICATE-----

###############################################################################
## Dependency Values                                                         ##
###############################################################################

postgresql:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 15.0.0-debian-11-r3
    pullPolicy: IfNotPresent
  auth:
    database: "application-data-db"
  tls:
    certificatesSecret: "existing-tls-secret"
  primary:
    resources:
      limits:
        memory: 0Mi
        cpu: 0m
      requests:
        memory: 0Mi
        cpu: 0m
  readReplicas:
    replicaCount: 1
    resources:
      limits:
        memory: 0Mi
        cpu: 0m
      requests:
        memory: 0Mi
        cpu: 0m
  volumePermissions:
    image:
      registry: docker.io
      repository: bitnami/bitnami-shell
      tag: 11-debian-11-r47
      pullPolicy: IfNotPresent
  metrics:
    image:
      registry: docker.io
      repository: bitnami/postgres-exporter
      tag: 0.11.1-debian-11-r24
      pullPolicy: IfNotPresent

redis:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: 7.0.5-debian-11-r15
    pullPolicy: IfNotPresent
  master:
    count: 1
    resources:
      limits:
        memory: 0Mi
        cpu: 0m
      requests:
        memory: 0Mi
        cpu: 0m
  replica:
    replicaCount: 1
    resources:
      limits:
        memory: 0Mi
        cpu: 0m
      requests:
        memory: 0Mi
        cpu: 0m
  sentinel:
    image:
      registry: docker.io
      repository: bitnami/redis-sentinel
      tag: 7.0.5-debian-11-r14
      pullPolicy: IfNotPresent
  tls:
    existingSecret: "existing-tls-secret"
  metrics:
    image:
      registry: docker.io
      repository: bitnami/redis-exporter
      tag: 1.45.0-debian-11-r1
      pullPolicy: IfNotPresent
  volumePermissions:
    image:
      registry: docker.io
      repository: bitnami/bitnami-shell
      tag: 11-debian-11-r48
      pullPolicy: IfNotPresent
  sysctl:
    image:
      registry: docker.io
      repository: bitnami/bitnami-shell
      tag: 11-debian-11-r48
      pullPolicy: IfNotPresent
