include:
  - project: tenant/tekton-promotion-gitlab
    #file: routes/container-only.yml
    file: routes/helm-only.yml
    #file: routes/dragon-full.yml

stages:
  - '🧪 unit-test'
  - pipeline-trigger

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "main" # && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH || $CI_JOB_MANUAL = true
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $HELM_ONLY == "false"
      variables:
        HELM_UPGRADE_EXTRA_ARGS: >-
          --set image.tag=${CI_COMMIT_SHA}
    - if: $HELM_ONLY == "true"
      variables:
        HELM_UPGRADE_EXTRA_ARGS: >-
          --set image.tag=${IMAGE_TAG_FOR_HELM_ONLY}


variables:
  HELM_ONLY:
    description: 'only build chart'
    value: 'true'
    options:
      - 'true'
      - 'false'
  IMAGE_TAG_FOR_HELM_ONLY:
    description: 'Image tag you want to use for only a helm config deploy (most likely your last commit sha on main)'
    value: '78ffabb8b0f0ee6ca14ff319a93defbc4b67e375' # ${CI_COMMIT_SHA}
  CONTAINER_ONLY:
    description: 'only build container'
    value: 'false'
    options:
      - 'true'
      - 'false'
  UPSTREAM_PROJECT_DIR: '.'
  HELM_RELEASE_NAME: 'advana-marketplace'
  HELM_CHART_DIR: './chart'
  DOCKERFILE_PATH: './Dockerfile'
