include:
  - project: promotion/tekton-promotion-gitlab
    file: routes/dragon-full.yml

variables:
  UPSTREAM_PROJECT_DIR: "."
  HELM_RELEASE_NAME: "advana-marketplace"
  HELM_CHART_DIR: "./chart"
  DOCKERFILE_PATH: "./Dockerfile.distroless"