---
apiVersion: database.advana.cdao.us/v1alpha1
kind: Postgres
metadata:
  name: node-example
  namespace: node-example
spec:
  region: us-gov-west-1
  dbName: node-example
  allocatedStorage: 40
  tags:
    application: "node-example"
    description: "template app rds"
    poc: "node-example@foo.bar"
    pocTeam: "node-example"
