apiVersion: v1
kind: Secret
metadata:
  name: public-env-platform-ui
  namespace: advana-marketplace
{{ include "common.env.secret" $ }}
{{ include "common.volume.secret" $ }}
{{ include "common.tls.secret" $ }}
{{ include "common.dockerconfigjson.secret" $ }}
