apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-advana-marketplace-web-clusterip
  namespace: advana-marketplace
  labels:
    app.kubernetes.io/name: advana-marketplace
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: advana-marketplace
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 7500
      targetPort: 7500
      protocol: TCP
    - name: httpx
      port: 8081
      targetPort: 8081
      protocol: TCP
{{ include "common.service" $ }}
