import { getEndpointUrl, isBypassAuth } from "../utils/api-config";
import { SessionService } from "./sessionService";
import type {
  Notification,
  NotificationPriority,
  NotificationRecipientApiResponse,
} from "../interfaces/interfaceStore";

// Custom error class for API errors
export class ApiError extends Error {
  statusCode: number;
  details?: string;

  constructor(message: string, statusCode: number, details?: string) {
    super(message);
    this.name =
      statusCode >= 500 && statusCode < 600 ? "ServerError" : "ApiError";
    this.statusCode = statusCode;
    this.details = details;

    // Maintains proper stack trace for where our error was thrown (only available on V8)
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, ApiError);
    }
  }
}

// Interface definitions for API requests and responses
export interface SubmitRequestApiRequest {
  requestNumber?: string; // Now generated by the backend; omit from frontend submissions
  requestorEmail: string;
  designation: string;
  agency: string;
  organization: string;
  otherOrganization: string;
  pointOfContact: string;
  email: string;
  phoneNumber: string;
  estimatedRom: string;
  requestedToolName: string;
  description: string;
  cartItems: CartItemApiDto[];
}

export interface CartItemApiDto {
  name: string;
  quantity: number;
}

export interface SubmitRequestApiResponse {
  requestNumber?: string;
  errMsg?: string;
}

export interface ViewRequestsApiRequest {
  userEmail: string;
}

export interface ViewRequestsApiResponse {
  requests?: UseCaseRequestApiDto[];
  errMsg?: string;
}

export interface ViewRequestByNumberApiRequest {
  userEmail: string;
  requestNumber: string;
}

export interface ViewRequestByNumberApiResponse {
  request?: UseCaseRequestApiDto;
  errMsg?: string;
}

export interface UseCaseRequestApiDto {
  requestNumber: string;
  statusId: number;
  requestorEmail: string;
  requestorUsername: string;
  designation: string;
  agency: string;
  organization: string;
  otherOrganization: string;
  pointOfContact: string;
  email: string;
  phoneNumber: string;
  requestedToolName: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  cartItems: CartItemApiDto[];
}

export type ChatMessageRole = "user" | "assistant";

export interface ChatHistoryItem {
  role: ChatMessageRole;
  content: string;
}

export interface ChatMessageApiRequest {
  message?: string;
  prompt?: string;
  conversationId?: string;
  history?: ChatHistoryItem[];
}

export interface ChatCitationApiDto {
  id?: string | number;
  title?: string;
  source?: string;
  url?: string;
  snippet?: string;
  text?: string;
}

export interface ChatProductApiDto {
  id?: string | number;
  name?: string;
  title?: string;
  type?: string;
  description?: string;
  price?: number | null;
  rom?: string;
  url?: string;
}

export interface ChatApiResponse {
  answer?: string;
  response?: string;
  message?: string;
  content?: string;
  text?: string;
  conversationId?: string;
  citations?: ChatCitationApiDto[];
  sources?: ChatCitationApiDto[];
  products?: ChatProductApiDto[];
  productCards?: ChatProductApiDto[];
  errMsg?: string;
}

function mapPriorityLevel(level: number): NotificationPriority {
  if (level === 1) return "high";
  if (level === 2) return "medium";
  return "low";
}

function mapNotificationDto(item: NotificationRecipientApiResponse): Notification {
  return {
    id: item.notification.id.toString(),
    type: "general",
    priority: mapPriorityLevel(item.notification.priorityLevel),
    title: item.notification.title,
    message: item.notification.message,
    read: item.read,
    createdAt: item.notification.createdAt,
  };
}

/**
 * API Service for communicating with the advana-marketplace-monolith backend
 */
export class ApiService {
  /**
   * Get authorization headers for API requests
   * Supports two modes:
   * 1. Session Storage Mode (USE_CLIENT_SESSION_STORAGE=true on backend):
   *    - Uses session ID in Authorization header
   * 2. Direct Token Mode (USE_CLIENT_SESSION_STORAGE=false on backend):
   *    - Uses Keycloak JWT token directly in Authorization header
   */
  private static async getAuthHeaders(): Promise<Record<string, string>> {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };

    // eslint-disable-next-line no-console
    console.log("[ApiService] 🔑 Getting auth headers...");

    try {
      // Check if session storage is enabled
      if (SessionService.isSessionStorageEnabled()) {
        // Mode 1: Use session ID
        const sessionId = SessionService.getSessionId();
        if (sessionId) {
          headers["Authorization"] = `Bearer ${sessionId}`;
          // eslint-disable-next-line no-console
          console.debug("[ApiService] Using session ID for authorization");
          return headers;
        } else {
          // eslint-disable-next-line no-console
          console.warn("[ApiService] Session storage enabled but no session ID found, falling back to direct token mode");
        }
      }

      // Mode 2: Use Keycloak token directly
      // Check if we're in bypass auth mode (development with mock Keycloak)
      const bypassAuth = import.meta.env.VITE_BYPASS_AUTH === "true";

      // Debug logging
      if (import.meta.env.DEV) {
        // eslint-disable-next-line no-console
        console.log("[ApiService] getAuthHeaders debug:", {
          bypassAuth,
          VITE_BYPASS_AUTH: import.meta.env.VITE_BYPASS_AUTH,
          // @ts-ignore
          hasWindowKeycloak: !!window.keycloak,
          // @ts-ignore
          isAuthenticated: window.keycloak?.authenticated,
          // @ts-ignore
          hasToken: !!window.keycloak?.token,
        });
      }

      if (bypassAuth) {
        // In bypass mode, get token from window.keycloak (mock Keycloak instance)
        // @ts-ignore - window.keycloak is set by MockKeycloakProvider
        const keycloak = window.keycloak;
        if (keycloak?.authenticated && keycloak.token) {
          headers["Authorization"] = `Bearer ${keycloak.token}`;
           
          if (import.meta.env.DEV) {
            // eslint-disable-next-line no-console
            console.log(
              "[ApiService] Added Authorization header (bypass mode)"
            );
          }
        } else {
          // If window.keycloak isn't ready yet, provide a dummy bypass token
          // This ensures the backend bypass logic still works
          const dummyToken = `mock.${window.btoa(
            JSON.stringify({
              sub: "bypass-user",
              email: "bypass@local.dev",
              preferred_username: "bypass-user",
              roles: [],
            })
          )}.signature`;
          headers["Authorization"] = `Bearer ${dummyToken}`;
          // eslint-disable-next-line no-console
          console.warn(
            "[ApiService] Using dummy bypass token (window.keycloak not ready yet)",
            {
              keycloakExists: !!keycloak,
              authenticated: keycloak?.authenticated,
              hasToken: !!keycloak?.token,
            }
          );
        }
      } else {
        // In production mode, use the initialized keycloak instance from window
        // The keycloak instance is set by main.tsx after ReactKeycloakProvider initializes it
        // @ts-ignore - window.keycloak is set by main.tsx after initialization
        const keycloak = window.keycloak;

        // eslint-disable-next-line no-console
        console.log("[ApiService] Production mode - checking keycloak", {
          keycloakExists: !!keycloak,
          authenticated: keycloak?.authenticated,
          hasToken: !!keycloak?.token,
          tokenLength: keycloak?.token?.length,
        });

        // Check if keycloak is authenticated and has a valid token
        if (keycloak?.authenticated && keycloak.token) {
          // Ensure token is fresh before using it (refresh if expires within 30 seconds)
          await keycloak.updateToken(30);
          headers["Authorization"] = `Bearer ${keycloak.token}`;
          // eslint-disable-next-line no-console
          console.log("[ApiService] ✅ Using Keycloak token for authorization", {
            tokenPreview: keycloak.token.substring(0, 20) + "...",
            tokenSet: !!headers["Authorization"]
          });
        } else {
          // eslint-disable-next-line no-console
          console.error("[ApiService] ❌ Keycloak not authenticated or no token available", {
            keycloakExists: !!keycloak,
            authenticated: keycloak?.authenticated,
            hasToken: !!keycloak?.token,
            windowKeycloakType: typeof window.keycloak,
          });
          // Log what's in window to help debug
          // eslint-disable-next-line no-console
          console.log("[ApiService] window.keycloak debug:", window.keycloak);
        }
      }
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error("[ApiService] Failed to get authentication token:", error);
      // Continue without token - let the backend handle unauthenticated requests
    }

    // eslint-disable-next-line no-console
    console.log("[ApiService] 🔑 Final headers:", {
      hasContentType: !!headers["Content-Type"],
      hasAuthorization: !!headers["Authorization"],
      authHeaderPreview: headers["Authorization"] ? headers["Authorization"].substring(0, 20) + "..." : "MISSING"
    });

    return headers;
  }

  /**
   * Handle API response errors
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private static async handleResponse<T>(response: any): Promise<T> {
    if (!response.ok) {
      let errorMessage = `HTTP error! status: ${response.status}`;
      let errorDetails = "";

      try {
        const errorData = await response.json();
        if (errorData.errMsg) {
          errorMessage = errorData.errMsg;
        } else if (errorData.message) {
          errorMessage = errorData.message;
        } else if (errorData.error) {
          errorMessage = errorData.error;
        }

        // Capture additional error details for debugging
        errorDetails = JSON.stringify(errorData);
      } catch {
        // If JSON parsing fails, use the default error message
      }

      // Log detailed error for debugging
      // eslint-disable-next-line no-console
      console.error(
        `API Error [${response.status}]:`,
        errorMessage,
        errorDetails ? `\nDetails: ${errorDetails}` : ""
      );

      // Throw structured error with status code
      throw new ApiError(errorMessage, response.status, errorDetails);
    }

    return response.json();
  }

  /**
   * Submit a new request to the backend
   */
  static async submitRequest(
    requestData: SubmitRequestApiRequest
  ): Promise<SubmitRequestApiResponse> {
    try {
      const headers = await this.getAuthHeaders();

      // Log request payload in development mode
      if (import.meta.env.DEV) {
        // eslint-disable-next-line no-console
        console.log(
          "[ApiService] submitRequest payload:",
          JSON.stringify(requestData, null, 2)
        );
      }

      const response = await window.fetch(getEndpointUrl("SUBMIT_REQUEST"), {
        method: "POST",
        headers: headers,
        body: JSON.stringify(requestData),
        mode: "cors",
        credentials: "omit",
      });

      // Log response status in development mode
      if (import.meta.env.DEV) {
        // eslint-disable-next-line no-console
        console.log(
          "[ApiService] submitRequest response status:",
          response.status
        );
      }

      return this.handleResponse<SubmitRequestApiResponse>(response);
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error("Error submitting request:", error);

      // Handle authentication errors gracefully
      if (error instanceof Error) {
        const errorMsg = error.message.toLowerCase();
        // eslint-disable-next-line no-console
        console.log(
          `[DEBUG submitRequest] Checking error message: "${errorMsg}"`
        );

        // Authentication/token validation issues
        if (
          errorMsg.includes("introspection") ||
          errorMsg.includes("unauthorized") ||
          errorMsg.includes("forbidden")
        ) {
          // eslint-disable-next-line no-console
          console.warn(
            `✅ Authentication error during request submission. Returning error response.`
          );
          return {
            requestNumber: undefined,
            errMsg:
              "Authentication failed. Please ensure you're logged in and try again.",
          };
        }
      }

      // In development mode with bypass auth, return a mock success response
      if (isBypassAuth) {
        // eslint-disable-next-line no-console
        console.log(
          "API call failed in bypass auth mode, returning mock success response"
        );
        return {
          requestNumber: `MOCK-${Date.now()}`,
          errMsg: undefined,
        };
      }

      throw error;
    }
  }

  /**
   * Send a Marketplace assistant prompt to the backend chat endpoint.
   */
  static async sendChatMessage(
    requestData: ChatMessageApiRequest
  ): Promise<ChatApiResponse> {
    const { prompt, ...requestWithoutDeprecatedPrompt } = requestData;
    const requestBody = {
      ...requestWithoutDeprecatedPrompt,
      ...(requestData.message || prompt
        ? { message: requestData.message || prompt }
        : {}),
    };

    const response = await window.fetch(getEndpointUrl("CHAT"), {
      method: "POST",
      headers: await this.getAuthHeaders(),
      body: JSON.stringify(requestBody),
      mode: "cors",
      credentials: "omit",
    });

    return this.handleResponse<ChatApiResponse>(response);
  }

  /**
   * Clear a Marketplace assistant conversation on the backend.
   */
  static async clearChatConversation(conversationId: string): Promise<void> {
    const response = await window.fetch(
      getEndpointUrl("CHAT_CONVERSATION", { conversationId }),
      {
        method: "DELETE",
        headers: await this.getAuthHeaders(),
        mode: "cors",
        credentials: "omit",
      }
    );

    if (response.status === 204 || response.status === 404) {
      return;
    }

    await this.handleResponse<unknown>(response);
  }

  /**
   * Get requests for a specific requestor
   */
  static async getRequestsForRequestor(
    userEmail: string
  ): Promise<ViewRequestsApiResponse> {
    try {
      const requestData: ViewRequestsApiRequest = { userEmail };

      const response = await window.fetch(
        getEndpointUrl("VIEW_FOR_REQUESTOR"),
        {
          method: "POST",
          headers: await this.getAuthHeaders(),
          body: JSON.stringify(requestData),
        }
      );

      return this.handleResponse<ViewRequestsApiResponse>(response);
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error("Error fetching requests for requestor:", error);

      // Handle common recoverable errors gracefully
      if (error instanceof Error) {
        const errorMsg = error.message.toLowerCase();
        // eslint-disable-next-line no-console
        console.log(`[DEBUG] Checking error message: "${errorMsg}"`);

        // User doesn't exist in database yet
        if (
          errorMsg.includes("not found") ||
          errorMsg.includes("user with email")
        ) {
          // eslint-disable-next-line no-console
          console.warn(
            `✅ User ${userEmail} not found in database. Returning empty requests list.`
          );
          return { requests: [] };
        }

        // Authentication/token validation issues
        if (
          errorMsg.includes("introspection") ||
          errorMsg.includes("unauthorized") ||
          errorMsg.includes("forbidden")
        ) {
          // eslint-disable-next-line no-console
          console.warn(
            `✅ Authentication error for user ${userEmail}. This may indicate token issues. Returning empty requests list.`
          );
          return { requests: [] };
        }
      }

      throw error;
    }
  }

  /**
   * Get all pending requests (for approvers)
   */
  static async getPendingRequests(
    userEmail: string
  ): Promise<ViewRequestsApiResponse> {
    try {
      const requestData: ViewRequestsApiRequest = { userEmail };

      const response = await window.fetch(getEndpointUrl("VIEW_PENDING"), {
        method: "POST",
        headers: await this.getAuthHeaders(),
        body: JSON.stringify(requestData),
      });

      return this.handleResponse<ViewRequestsApiResponse>(response);
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error("Error fetching pending requests:", error);

      // Handle common recoverable errors gracefully
      if (error instanceof Error) {
        const errorMsg = error.message.toLowerCase();

        // User doesn't exist in database yet
        if (
          errorMsg.includes("not found") ||
          errorMsg.includes("user with email")
        ) {
          // eslint-disable-next-line no-console
          console.warn(
            `User ${userEmail} not found in database. Returning empty pending requests list.`
          );
          return { requests: [] };
        }

        // Authentication/token validation issues
        if (
          errorMsg.includes("introspection") ||
          errorMsg.includes("unauthorized") ||
          errorMsg.includes("forbidden")
        ) {
          // eslint-disable-next-line no-console
          console.warn(
            `Authentication error for user ${userEmail}. This may indicate token issues. Returning empty pending requests list.`
          );
          return { requests: [] };
        }
      }

      throw error;
    }
  }

  /**
   * Get all requests (for approvers)
   */
  static async getAllRequests(
    userEmail: string
  ): Promise<ViewRequestsApiResponse> {
    try {
      const requestData: ViewRequestsApiRequest = { userEmail };

      const response = await window.fetch(getEndpointUrl("VIEW_ALL"), {
        method: "POST",
        headers: await this.getAuthHeaders(),
        body: JSON.stringify(requestData),
      });

      return this.handleResponse<ViewRequestsApiResponse>(response);
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error("Error fetching all requests:", error);

      // Handle common recoverable errors gracefully
      if (error instanceof Error) {
        const errorMsg = error.message.toLowerCase();

        // User doesn't exist in database yet
        if (
          errorMsg.includes("not found") ||
          errorMsg.includes("user with email")
        ) {
          // eslint-disable-next-line no-console
          console.warn(
            `User ${userEmail} not found in database. Returning empty requests list.`
          );
          return { requests: [] };
        }

        // Authentication/token validation issues
        if (
          errorMsg.includes("introspection") ||
          errorMsg.includes("unauthorized") ||
          errorMsg.includes("forbidden")
        ) {
          // eslint-disable-next-line no-console
          console.warn(
            `Authentication error for user ${userEmail}. This may indicate token issues. Returning empty requests list.`
          );
          return { requests: [] };
        }
      }

      throw error;
    }
  }

  /**
   * Get a specific request by request number
   * NOTE: Temporarily includes fallback logic until local backend is updated
   */
  static async getRequestByNumber(
    userEmail: string,
    requestNumber: string
  ): Promise<ViewRequestByNumberApiResponse> {
    try {
      const requestData: ViewRequestByNumberApiRequest = {
        userEmail,
        requestNumber,
      };

      const response = await window.fetch(
        getEndpointUrl("VIEW_FOR_REQUEST_NUMBER"),
        {
          method: "POST",
          headers: await this.getAuthHeaders(),
          body: JSON.stringify(requestData),
        }
      );

      // Temporary fallback for local development until backend is updated
      if (response.status === 501) {
        // eslint-disable-next-line no-console
        console.warn(
          "⚠️ Local backend not updated yet, falling back to getAllRequests"
        );

        // Fall back to getAllRequests and filter client-side
        const allRequestsResponse = await this.getAllRequests(userEmail);

        if (allRequestsResponse.requests) {
          const foundRequest = allRequestsResponse.requests.find(
            (req: UseCaseRequestApiDto) =>
              req.requestNumber?.toString() === requestNumber
          );

          return {
            request: foundRequest || undefined,
            errMsg: foundRequest ? "" : "Request not found",
          };
        }

        return {
          request: undefined,
          errMsg: "No requests found",
        };
      }

      // Handle the actual API response structure
      const responseData = await this.handleResponse<UseCaseRequestApiDto>(
        response
      );

      // The API returns the request data directly, not wrapped in a "request" property
      return {
        request: responseData,
        errMsg: "",
      };
    } catch (error) {
      // Check if this is an authorization error and fall back to existing endpoints
      if (
        error instanceof Error &&
        error.message.includes("UnauthorizedAdjudicatorError")
      ) {
        // eslint-disable-next-line no-console
        console.warn(
          "⚠️ User not authorized as adjudicator for new endpoint, falling back to existing endpoints"
        );

        try {
          // Try requestor-specific endpoint first, then fall back to getAllRequests
          let allRequestsResponse: ViewRequestsApiResponse;

          try {
            allRequestsResponse = await this.getRequestsForRequestor(userEmail);
          } catch {
            // If requestor endpoint fails, try getAllRequests
            allRequestsResponse = await this.getAllRequests(userEmail);
          }

          if (allRequestsResponse.requests) {
            const foundRequest = allRequestsResponse.requests.find(
              (req: UseCaseRequestApiDto) =>
                req.requestNumber?.toString() === requestNumber
            );

            return {
              request: foundRequest || undefined,
              errMsg: foundRequest ? "" : "Request not found",
            };
          }

          return {
            request: undefined,
            errMsg: "No requests found",
          };
        } catch (fallbackError) {
          // eslint-disable-next-line no-console
          console.error("Error in authorization fallback:", fallbackError);
          throw fallbackError;
        }
      }

      // eslint-disable-next-line no-console
      console.error("Error fetching request by number:", error);
      throw error;
    }
  }

  /**
   * Get notifications for the authenticated user from the backend.
   * The backend filters by the current user's identity via the auth token.
   */
  static async getNotifications(): Promise<Notification[]> {
    try {
      const response = await window.fetch(
        getEndpointUrl("NOTIFICATION_RECIPIENTS"),
        {
          method: "GET",
          headers: await this.getAuthHeaders(),
        }
      );
      const data =
        await this.handleResponse<NotificationRecipientApiResponse[]>(response);
      return data.map(mapNotificationDto);
    } catch (error) {
      if (error instanceof Error) {
        const errorMsg = error.message.toLowerCase();
        if (
          errorMsg.includes("not found") ||
          errorMsg.includes("unauthorized") ||
          errorMsg.includes("forbidden") ||
          errorMsg.includes("introspection")
        ) {
          return [];
        }
      }
      // eslint-disable-next-line no-console
      console.error("Error fetching notifications:", error);
      return [];
    }
  }

  /**
   * Make a decision on a request (approve/reject)
   */
  static async makeDecision(decisionData: unknown): Promise<unknown> {
    try {
      const response = await window.fetch(getEndpointUrl("DECISIONS"), {
        method: "POST",
        headers: await this.getAuthHeaders(),
        body: JSON.stringify(decisionData),
      });

      return this.handleResponse<unknown>(response);
    } catch (error) {
      // eslint-disable-next-line no-console
      console.error("Error making decision:", error);
      throw error;
    }
  }
}
